import { Selector } from 'testcafe';

fixture `testPerson`
    .page `http://live.semantic-machines.com/`;
test('testPerson', async t => {
    const user = 'Стивен Эдвин Кинг';
    const user1 = 'Говард Филлипс Лавкрафт';
    await t
    .typeText('#login', 'karpovrt')
    .typeText('#password', '123')
    .click('#submit')
    .expect(Selector('#user-info').innerText).eql('Администратор2\n')
    .click('#menu')
    .click('li[id="menu"] li[resource="v-l:Create"]')
    .typeText('veda-control.fulltext.dropdown', 'Персона')
    .click('div.suggestion[about="v-s:Person"]')
    .click('veda-control.-view.edit.search[property="v-s:birthday"]')
    .typeText('veda-control.-view.edit.search[property="v-s:lastName"]', 'Кинг')
    .typeText('veda-control.-view.edit.search.has-error[property="v-s:firstName"]', 'Стивен')
    .typeText('veda-control.-view.edit.search[property="v-s:middleName"]', 'Эдвин')
    .typeText('veda-control.-view.edit.search[property="rdfs:label"]', user)
    .wait(1000)
    .click('span[data-template="v-ui:StandardButtonsTemplate"] span[typeof="v-s:Person"] button#save')
    .click('#menu')
    .click('li[id="menu"] li[resource="v-l:Exit"]')
    .click('#login')
    .pressKey('ctrl+a delete')
    .typeText('#login', 'bychinat')
    .click('#submit')
    .expect(Selector('#user-info').innerText).eql('Администратор4\n')
    //для поиска через меню
    //.click('#menu')
    //.click('li[id="menu"] li[resource="v-l:Find"]')
    //.typeText('input.form-control[name="v_fs_fulltextrequest_v_fs_fulltextquery"]', user)
    //.typeText('veda-control.fulltext.dropdown', 'Персона')
    //.click('div.suggestion[about="v-s:Person"]')
    //.click('span.input-group-btn button#submit')
    //для поиска через v-fs:FulltextSearch
    .click('ul.nav.navbar-nav.navbar-right li[about="v-fs:FulltextSearch"]')
    .typeText('div.input-group input[name="v_s_userthing_*"]', user)
    .click('span.input-group-btn button[about="v-fs:Find"]')
    .expect(Selector('div.not-found.alert.alert-warning strong[about="v-fs:Empty"]').innerText).eql('Пусто!')
    .click('#menu')
    .click('li[id="menu"] li[resource="v-l:Create"]')
    .typeText('veda-control.fulltext.dropdown', 'Персона')
    .click('div.suggestion[about="v-s:Person"]')
    .click('veda-control.-view.edit.search[property="v-s:birthday"]')
    .typeText('veda-control.-view.edit.search[property="v-s:lastName"]', 'Лавкрафт')
    .typeText('veda-control.-view.edit.search.has-error[property="v-s:firstName"]', 'Говард')
    .typeText('veda-control.-view.edit.search[property="v-s:middleName"]', 'Филлипс')
    .typeText('veda-control.-view.edit.search[property="rdfs:label"]', user1)
    .wait(1000)
    .click('span[data-template="v-ui:StandardButtonsTemplate"] span[typeof="v-s:Person"] button#save')
    .click('#menu')
    .click('li[id="menu"] li[resource="v-l:Exit"]')
    .click('#login')
    .pressKey('ctrl+a delete')
    .typeText('#login', 'karpovrt')
    .click('#submit')
    .expect(Selector('#user-info').innerText).eql('Администратор2\n')
    .click('ul.nav.navbar-nav.navbar-right li[about="v-fs:FulltextSearch"]')
    .typeText('div.input-group input[name="v_s_userthing_*"]', user1)
    .click('span.input-group-btn button[about="v-fs:Find"]')
    .click('tbody.result-container a.glyphicon.glyphicon-search')
    .expect(Selector('h3 span[property="rdfs:label"] span.value-holder').innerText).eql('Говард Филлипс Лавкрафт')
});
