/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;
#[allow(unused_imports)]
use std::option::Option;

use reqwest;

use super::{Error, configuration};

pub struct MessageApiClient {
    configuration: Rc<configuration::Configuration>,
}

impl MessageApiClient {
    pub fn new(configuration: Rc<configuration::Configuration>) -> MessageApiClient {
        MessageApiClient {
            configuration,
        }
    }
}

pub trait MessageApi {
    fn deliver_message(&self, correlation_message_dto: Option<crate::models::CorrelationMessageDto>) -> Result<Vec<crate::models::MessageCorrelationResultWithVariableDto>, Error>;
}

impl MessageApi for MessageApiClient {
    fn deliver_message(&self, correlation_message_dto: Option<crate::models::CorrelationMessageDto>) -> Result<Vec<crate::models::MessageCorrelationResultWithVariableDto>, Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        let client = &configuration.client;

        let uri_str = format!("{}/message", configuration.base_path);
        let mut req_builder = client.post(uri_str.as_str());

        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }
        req_builder = req_builder.json(&correlation_message_dto);

        // send request
        let req = req_builder.build()?;

        Ok(client.execute(req)?.error_for_status()?.json()?)
    }

}
