import './polyfills.js';

import {describe, it} from 'beartest-js';
import assert from 'assert';
import Backend from '../../js/browser/backend_browser.js';
import Helpers from './helpers.js';
import Constants from './constants.js';
import ServerUtil from '../../js/server/util.js';
import CommonUtil from '../../js/common/util.js';
const Util = {...ServerUtil, ...CommonUtil};

import test001 from './test001.js';
import test002 from './test002.js';
import test003 from './test003.js';
import test004 from './test004.js';
import test005 from './test005.js';
import test006 from './test006.js';
import test007 from './test007.js';
import test008 from './test008.js';
import test009 from './test009.js';
import test010 from './test010.js';
import test011 from './test011.js';
import test012 from './test012.js';
import test013 from './test013.js';
import test014 from './test014.js';
import test015 from './test015.js';
import test016 from './test016.js';
import test017 from './test017.js';
import test018 from './test018.js';
import test019 from './test019.js';
import test020 from './test020.js';
import test021 from './test021.js';
import test022 from './test022.js';
import test023 from './test023.js';
import test024 from './test024.js';
import test025 from './test025.js';
import test026 from './test026.js';
import test027 from './test027.js';
import test028 from './test028.js';
import test029 from './test029.js';
import test030 from './test030.js';
import test031 from './test031.js';
import test032 from './test032.js';
import test033 from './test033.js';
import test034 from './test034.js';
import test035 from './test035.js';
import test036 from './test036.js';
import test037 from './test037.js';
import test038 from './test038.js';
import test039 from './test039.js';
import test040 from './test040.js';
import test041 from './test041.js';
import test042 from './test042.js';

describe('Backend tests', () => {
  test001({it, assert, Backend, Helpers, Constants, Util});
  test002({it, assert, Backend, Helpers, Constants, Util});
  test003({it, assert, Backend, Helpers, Constants, Util});
  test004({it, assert, Backend, Helpers, Constants, Util});
  test005({it, assert, Backend, Helpers, Constants, Util});
  test006({it, assert, Backend, Helpers, Constants, Util});
  test007({it, assert, Backend, Helpers, Constants, Util});
  test008({it, assert, Backend, Helpers, Constants, Util});
  test009({it, assert, Backend, Helpers, Constants, Util});
  test010({it, assert, Backend, Helpers, Constants, Util});
  test011({it, assert, Backend, Helpers, Constants, Util});
  test012({it, assert, Backend, Helpers, Constants, Util});
  test013({it, assert, Backend, Helpers, Constants, Util});
  test014({it, assert, Backend, Helpers, Constants, Util});
  test015({it, assert, Backend, Helpers, Constants, Util});
  test016({it, assert, Backend, Helpers, Constants, Util});
  test017({it, assert, Backend, Helpers, Constants, Util});
  test018({it, assert, Backend, Helpers, Constants, Util});
  test019({it, assert, Backend, Helpers, Constants, Util});
  test020({it, assert, Backend, Helpers, Constants, Util});
  test021({it, assert, Backend, Helpers, Constants, Util});
  test022({it, assert, Backend, Helpers, Constants, Util});
  test023({it, assert, Backend, Helpers, Constants, Util});
  test024({it, assert, Backend, Helpers, Constants, Util});
  test025({it, assert, Backend, Helpers, Constants, Util});
  test026({it, assert, Backend, Helpers, Constants, Util});
  test027({it, assert, Backend, Helpers, Constants, Util});
  test028({it, assert, Backend, Helpers, Constants, Util});
  test029({it, assert, Backend, Helpers, Constants, Util});
  test030({it, assert, Backend, Helpers, Constants, Util});
  test031({it, assert, Backend, Helpers, Constants, Util});
  test032({it, assert, Backend, Helpers, Constants, Util});
  test033({it, assert, Backend, Helpers, Constants, Util});
  test034({it, assert, Backend, Helpers, Constants, Util});
  test035({it, assert, Backend, Helpers, Constants, Util});
  test036({it, assert, Backend, Helpers, Constants, Util});
  test037({it, assert, Backend, Helpers, Constants, Util});
  test038({it, assert, Backend, Helpers, Constants, Util});
  test039({it, assert, Backend, Helpers, Constants, Util});
  test040({it, assert, Backend, Helpers, Constants, Util});
  test041({it, assert, Backend, Helpers, Constants, Util});
  test042({it, assert, Backend, Helpers, Constants, Util});
});
