import './polyfills.js';

import {describe, it} from 'beartest-js';
import assert from 'assert';
import Backend from '../../js/browser/backend_browser.js';
import Helpers from './helpers.js';
import Constants from './constants.js';
import ServerUtil from '../../js/server/util.js';
import CommonUtil from '../../js/common/util.js';
const Util = {...ServerUtil, ...CommonUtil};

import test1 from './test1.js';
import test2 from './test2.js';
import test3 from './test3.js';
import test4 from './test4.js';
import test5 from './test5.js';
import test6 from './test6.js';
import test7 from './test7.js';
import test8 from './test8.js';
import test9 from './test9.js';
import test10 from './test10.js';
import test11 from './test11.js';
import test12 from './test12.js';
import test13 from './test13.js';
import test14 from './test14.js';
import test15 from './test15.js';
import test16 from './test16.js';
import test17 from './test17.js';
import test18 from './test18.js';
import test19 from './test19.js';
import test20 from './test20.js';
import test21 from './test21.js';
import test22 from './test22.js';
import test23 from './test23.js';
import test24 from './test24.js';
import test25 from './test25.js';
import test26 from './test26.js';
import test27 from './test27.js';
import test28 from './test28.js';
import test29 from './test29.js';
import test30 from './test30.js';
import test31 from './test31.js';
import test32 from './test32.js';
import test33 from './test33.js';
import test34 from './test34.js';
import test35 from './test35.js';
import test36 from './test36.js';
import test37 from './test37.js';
import test38 from './test38.js';
import test39 from './test39.js';
import test40 from './test40.js';
import test41 from './test41.js';
import test42 from './test42.js';

describe('Backend tests', () => {
  test1({it, assert, Backend, Helpers, Constants, Util});
  test2({it, assert, Backend, Helpers, Constants, Util});
  test3({it, assert, Backend, Helpers, Constants, Util});
  test4({it, assert, Backend, Helpers, Constants, Util});
  test5({it, assert, Backend, Helpers, Constants, Util});
  test6({it, assert, Backend, Helpers, Constants, Util});
  test7({it, assert, Backend, Helpers, Constants, Util});
  test8({it, assert, Backend, Helpers, Constants, Util});
  test9({it, assert, Backend, Helpers, Constants, Util});
  test10({it, assert, Backend, Helpers, Constants, Util});
  test11({it, assert, Backend, Helpers, Constants, Util});
  test12({it, assert, Backend, Helpers, Constants, Util});
  test13({it, assert, Backend, Helpers, Constants, Util});
  test14({it, assert, Backend, Helpers, Constants, Util});
  test15({it, assert, Backend, Helpers, Constants, Util});
  test16({it, assert, Backend, Helpers, Constants, Util});
  test17({it, assert, Backend, Helpers, Constants, Util});
  test18({it, assert, Backend, Helpers, Constants, Util});
  test19({it, assert, Backend, Helpers, Constants, Util});
  test20({it, assert, Backend, Helpers, Constants, Util});
  test21({it, assert, Backend, Helpers, Constants, Util});
  test22({it, assert, Backend, Helpers, Constants, Util});
  test23({it, assert, Backend, Helpers, Constants, Util});
  test24({it, assert, Backend, Helpers, Constants, Util});
  test25({it, assert, Backend, Helpers, Constants, Util});
  test26({it, assert, Backend, Helpers, Constants, Util});
  test27({it, assert, Backend, Helpers, Constants, Util});
  test28({it, assert, Backend, Helpers, Constants, Util});
  test29({it, assert, Backend, Helpers, Constants, Util});
  test30({it, assert, Backend, Helpers, Constants, Util});
  test31({it, assert, Backend, Helpers, Constants, Util});
  test32({it, assert, Backend, Helpers, Constants, Util});
  test33({it, assert, Backend, Helpers, Constants, Util});
  test34({it, assert, Backend, Helpers, Constants, Util});
  test35({it, assert, Backend, Helpers, Constants, Util});
  test36({it, assert, Backend, Helpers, Constants, Util});
  test37({it, assert, Backend, Helpers, Constants, Util});
  test38({it, assert, Backend, Helpers, Constants, Util});
  test39({it, assert, Backend, Helpers, Constants, Util});
  test40({it, assert, Backend, Helpers, Constants, Util});
  test41({it, assert, Backend, Helpers, Constants, Util});
  test42({it, assert, Backend, Helpers, Constants, Util});
});
