/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ActivityInstanceIncidentDto : An activity instance, incident pair.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActivityInstanceIncidentDto {
    /// The id of the incident.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The activity id in which the incident happened.
    #[serde(rename = "parentActivityInstanceId", skip_serializing_if = "Option::is_none")]
    pub parent_activity_instance_id: Option<String>,
}

impl ActivityInstanceIncidentDto {
    /// An activity instance, incident pair.
    pub fn new() -> ActivityInstanceIncidentDto {
        ActivityInstanceIncidentDto {
            id: None,
            parent_activity_instance_id: None,
        }
    }
}


