/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteExternalTaskDto {
    /// The id of the worker that completes the task. Must match the id of the worker who has most recently locked the task.
    #[serde(rename = "workerId", skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    /// A JSON object containing variable key-value pairs. Each key is a variable name and each value a JSON variable value object with the following properties:
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<::std::collections::HashMap<String, crate::models::VariableValueDto>>,
    /// A JSON object containing local variable key-value pairs. Local variables are set only in the scope of external task. Each key is a variable name and each value a JSON variable value object with the following properties:
    #[serde(rename = "localVariables", skip_serializing_if = "Option::is_none")]
    pub local_variables: Option<::std::collections::HashMap<String, crate::models::VariableValueDto>>,
}

impl CompleteExternalTaskDto {
    pub fn new() -> CompleteExternalTaskDto {
        CompleteExternalTaskDto {
            worker_id: None,
            variables: None,
            local_variables: None,
        }
    }
}


