/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteTaskDto {
    /// A JSON object containing variable key-value pairs.
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<::std::collections::HashMap<String, crate::models::VariableValueDto>>,
    /// Indicates whether the response should contain the process variables or not. The default is `false` with a response code of `204`. If set to `true` the response contains the process variables and has a response code of `200`. If the task is not associated with a process instance (e.g. if it's part of a case instance) no variables will be returned.
    #[serde(rename = "withVariablesInReturn", skip_serializing_if = "Option::is_none")]
    pub with_variables_in_return: Option<bool>,
}

impl CompleteTaskDto {
    pub fn new() -> CompleteTaskDto {
        CompleteTaskDto {
            variables: None,
            with_variables_in_return: None,
        }
    }
}


