/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteHistoricProcessInstancesDto {
    /// A list historic process instance ids to delete.
    #[serde(rename = "historicProcessInstanceIds", skip_serializing_if = "Option::is_none")]
    pub historic_process_instance_ids: Option<Vec<String>>,
    #[serde(rename = "historicProcessInstanceQuery", skip_serializing_if = "Option::is_none")]
    pub historic_process_instance_query: Option<crate::models::HistoricProcessInstanceQueryDto>,
    /// A string with delete reason.
    #[serde(rename = "deleteReason", skip_serializing_if = "Option::is_none")]
    pub delete_reason: Option<String>,
    /// If set to `false`, the request will still be successful if one ore more of the process ids are not found.
    #[serde(rename = "failIfNotExists", skip_serializing_if = "Option::is_none")]
    pub fail_if_not_exists: Option<bool>,
}

impl DeleteHistoricProcessInstancesDto {
    pub fn new() -> DeleteHistoricProcessInstancesDto {
        DeleteHistoricProcessInstancesDto {
            historic_process_instance_ids: None,
            historic_process_instance_query: None,
            delete_reason: None,
            fail_if_not_exists: None,
        }
    }
}


