/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentWithDefinitionsDto {
    /// A JSON Object containing a property for each of the process definitions, which are successfully deployed with that deployment. The key is the process definition id, the value is a JSON Object corresponding to the process definition.
    #[serde(rename = "deployedProcessDefinitions", skip_serializing_if = "Option::is_none")]
    pub deployed_process_definitions: Option<::std::collections::HashMap<String, crate::models::ProcessDefinitionDto>>,
    /// A JSON Object containing a property for each of the decision definitions, which are successfully deployed with that deployment. The key is the decision definition id, the value is a JSON Object corresponding to the decision definition.
    #[serde(rename = "deployedDecisionDefinitions", skip_serializing_if = "Option::is_none")]
    pub deployed_decision_definitions: Option<::std::collections::HashMap<String, crate::models::DecisionDefinitionDto>>,
    /// A JSON Object containing a property for each of the decision requirements definitions, which are successfully deployed with that deployment. The key is the decision requirements definition id, the value is a JSON Object corresponding to the decision requirements definition.
    #[serde(rename = "deployedDecisionRequirementsDefinitions", skip_serializing_if = "Option::is_none")]
    pub deployed_decision_requirements_definitions: Option<::std::collections::HashMap<String, crate::models::DecisionRequirementsDefinitionDto>>,
    /// A JSON Object containing a property for each of the case definitions, which are successfully deployed with that deployment. The key is the case definition id, the value is a JSON Object corresponding to the case definition.
    #[serde(rename = "deployedCaseDefinitions", skip_serializing_if = "Option::is_none")]
    pub deployed_case_definitions: Option<::std::collections::HashMap<String, crate::models::CaseDefinitionDto>>,
    /// The id of the deployment.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The tenant id of the deployment.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
    /// The time when the deployment was created.
    #[serde(rename = "deploymentTime", skip_serializing_if = "Option::is_none")]
    pub deployment_time: Option<String>,
    /// The source of the deployment.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
    /// The name of the deployment.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The links associated to this resource, with `method`, `href` and `rel`.
    #[serde(rename = "links", skip_serializing_if = "Option::is_none")]
    pub links: Option<Vec<crate::models::AtomLink>>,
}

impl DeploymentWithDefinitionsDto {
    pub fn new() -> DeploymentWithDefinitionsDto {
        DeploymentWithDefinitionsDto {
            deployed_process_definitions: None,
            deployed_decision_definitions: None,
            deployed_decision_requirements_definitions: None,
            deployed_case_definitions: None,
            id: None,
            tenant_id: None,
            deployment_time: None,
            source: None,
            name: None,
            links: None,
        }
    }
}


