/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeploymentResourceDto : A JSON object corresponding to the `Resource` interface in the engine. Its properties are as follows:



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeploymentResourceDto {
    /// The id of the deployment resource.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The name of the deployment resource
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The id of the deployment.
    #[serde(rename = "deploymentId", skip_serializing_if = "Option::is_none")]
    pub deployment_id: Option<String>,
}

impl DeploymentResourceDto {
    /// A JSON object corresponding to the `Resource` interface in the engine. Its properties are as follows:
    pub fn new() -> DeploymentResourceDto {
        DeploymentResourceDto {
            id: None,
            name: None,
            deployment_id: None,
        }
    }
}


