/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventSubscriptionDto {
    /// The id of the event subscription.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the event subscription.
    #[serde(rename = "eventType", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<String>,
    /// The name of the event this subscription belongs to as defined in the process model.
    #[serde(rename = "eventName", skip_serializing_if = "Option::is_none")]
    pub event_name: Option<String>,
    /// The execution that is subscribed on the referenced event.
    #[serde(rename = "executionId", skip_serializing_if = "Option::is_none")]
    pub execution_id: Option<String>,
    /// The process instance this subscription belongs to.
    #[serde(rename = "processInstanceId", skip_serializing_if = "Option::is_none")]
    pub process_instance_id: Option<String>,
    /// The identifier of the activity that this event subscription belongs to. This could for example be the id of a receive task.
    #[serde(rename = "activityId", skip_serializing_if = "Option::is_none")]
    pub activity_id: Option<String>,
    /// The time this event subscription was created.
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    /// The id of the tenant this event subscription belongs to. Can be `null` if the subscription belongs to no single tenant.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl EventSubscriptionDto {
    pub fn new() -> EventSubscriptionDto {
        EventSubscriptionDto {
            id: None,
            event_type: None,
            event_name: None,
            execution_id: None,
            process_instance_id: None,
            activity_id: None,
            created_date: None,
            tenant_id: None,
        }
    }
}


