/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecutionDto {
    /// The id of the Execution.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The id of the root of the execution tree representing the process instance.
    #[serde(rename = "processInstanceId", skip_serializing_if = "Option::is_none")]
    pub process_instance_id: Option<String>,
    /// Indicates if the execution is ended.
    #[serde(rename = "ended", skip_serializing_if = "Option::is_none")]
    pub ended: Option<bool>,
    /// The id of the tenant this execution belongs to. Can be `null` if the execution belongs to no single tenant.
    #[serde(rename = "tenantId", skip_serializing_if = "Option::is_none")]
    pub tenant_id: Option<String>,
}

impl ExecutionDto {
    pub fn new() -> ExecutionDto {
        ExecutionDto {
            id: None,
            process_instance_id: None,
            ended: None,
            tenant_id: None,
        }
    }
}


