/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExtendLockOnExternalTaskDto {
    /// The ID of a worker who is locking the external task.
    #[serde(rename = "workerId", skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
    /// An amount of time (in milliseconds). This is the new lock duration starting from the current moment.
    #[serde(rename = "newDuration", skip_serializing_if = "Option::is_none")]
    pub new_duration: Option<i64>,
}

impl ExtendLockOnExternalTaskDto {
    pub fn new() -> ExtendLockOnExternalTaskDto {
        ExtendLockOnExternalTaskDto {
            worker_id: None,
            new_duration: None,
        }
    }
}


