/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalTaskBpmnErrorAllOf {
    /// The id of the worker that reports the failure. Must match the id of the worker who has most recently locked the task.
    #[serde(rename = "workerId", skip_serializing_if = "Option::is_none")]
    pub worker_id: Option<String>,
}

impl ExternalTaskBpmnErrorAllOf {
    pub fn new() -> ExternalTaskBpmnErrorAllOf {
        ExternalTaskBpmnErrorAllOf {
            worker_id: None,
        }
    }
}


