/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentityLinkDto {
    /// The id of the user participating in this link. Either `userId` or `groupId` is set.
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// The id of the group participating in this link. Either `groupId` or `userId` is set.
    #[serde(rename = "groupId", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
    /// The type of the identity link. The value of the this property can be user-defined. The Process Engine provides three pre-defined Identity Link `type`s:  * `candidate` * `assignee` - reserved for the task assignee * `owner` - reserved for the task owner  **Note**: When adding or removing an Identity Link, the `type` property must be defined.
    #[serde(rename = "type")]
    pub _type: String,
}

impl IdentityLinkDto {
    pub fn new(_type: String) -> IdentityLinkDto {
        IdentityLinkDto {
            user_id: None,
            group_id: None,
            _type,
        }
    }
}


