/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiFormVariableBinaryDto {
    /// The binary data to be set. For File variables, this multipart can contain the filename, binary value and MIME type of the file variable to be set Only the filename is mandatory.
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<std::path::PathBuf>,
    /// The name of the variable type. Either Bytes for a byte array variable or File for a file variable.
    #[serde(rename = "valueType", skip_serializing_if = "Option::is_none")]
    pub value_type: Option<ValueType>,
}

impl MultiFormVariableBinaryDto {
    pub fn new() -> MultiFormVariableBinaryDto {
        MultiFormVariableBinaryDto {
            data: None,
            value_type: None,
        }
    }
}

/// The name of the variable type. Either Bytes for a byte array variable or File for a file variable.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ValueType {
    #[serde(rename = "Bytes")]
    Bytes,
    #[serde(rename = "File")]
    File,
}

