/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MultiFormAttachmentDto {
    /// The name of the attachment.
    #[serde(rename = "attachment-name", skip_serializing_if = "Option::is_none")]
    pub attachment_name: Option<String>,
    /// The description of the attachment.
    #[serde(rename = "attachment-description", skip_serializing_if = "Option::is_none")]
    pub attachment_description: Option<String>,
    /// The type of the attachment.
    #[serde(rename = "attachment-type", skip_serializing_if = "Option::is_none")]
    pub attachment_type: Option<String>,
    /// The url to the remote content of the attachment.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The content of the attachment.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<std::path::PathBuf>,
}

impl MultiFormAttachmentDto {
    pub fn new() -> MultiFormAttachmentDto {
        MultiFormAttachmentDto {
            attachment_name: None,
            attachment_description: None,
            attachment_type: None,
            url: None,
            content: None,
        }
    }
}


