/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParseExceptionDto {
    /// A JSON Object containing list of errors and warnings occurred during deployment.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<::std::collections::HashMap<String, crate::models::ResourceReportDto>>,
    /// An exception class indicating the occurred error.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
    /// A detailed message of the error.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

impl ParseExceptionDto {
    pub fn new() -> ParseExceptionDto {
        ParseExceptionDto {
            details: None,
            _type: None,
            message: None,
        }
    }
}


