/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParseExceptionDtoAllOf {
    /// A JSON Object containing list of errors and warnings occurred during deployment.
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<::std::collections::HashMap<String, crate::models::ResourceReportDto>>,
}

impl ParseExceptionDtoAllOf {
    pub fn new() -> ParseExceptionDtoAllOf {
        ParseExceptionDtoAllOf {
            details: None,
        }
    }
}


