/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchVariablesDto {
    /// A JSON object containing variable key-value pairs.
    #[serde(rename = "modifications", skip_serializing_if = "Option::is_none")]
    pub modifications: Option<::std::collections::HashMap<String, crate::models::VariableValueDto>>,
    /// An array of String keys of variables to be deleted.
    #[serde(rename = "deletions", skip_serializing_if = "Option::is_none")]
    pub deletions: Option<Vec<String>>,
}

impl PatchVariablesDto {
    pub fn new() -> PatchVariablesDto {
        PatchVariablesDto {
            modifications: None,
            deletions: None,
        }
    }
}


