/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProblemDto {
    /// The message of the problem.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The line where the problem occurred.
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<i32>,
    /// The column where the problem occurred.
    #[serde(rename = "column", skip_serializing_if = "Option::is_none")]
    pub column: Option<i32>,
    /// The main element id where the problem occurred.
    #[serde(rename = "mainElementId", skip_serializing_if = "Option::is_none")]
    pub main_element_id: Option<String>,
    /// A list of element id affected by the problem.
    #[serde(rename = "elementIds", skip_serializing_if = "Option::is_none")]
    pub element_ids: Option<Vec<String>>,
}

impl ProblemDto {
    pub fn new() -> ProblemDto {
        ProblemDto {
            message: None,
            line: None,
            column: None,
            main_element_id: None,
            element_ids: None,
        }
    }
}


