/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceModificationInstructionDto {
    /// **Mandatory**. One of the following values: `cancel`, `startBeforeActivity`, `startAfterActivity`, `startTransition`.  * A cancel instruction requests cancellation of a single activity instance or all instances of one activity. * A startBeforeActivity instruction requests to enter a given activity. * A startAfterActivity instruction requests to execute the single outgoing sequence flow of a given activity. * A startTransition instruction requests to execute a specific sequence flow.
    #[serde(rename = "type")]
    pub _type: Type,
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<crate::models::TriggerVariableValueDto>,
    /// Can be used with instructions of types `startTransition`. Specifies the sequence flow to start.
    #[serde(rename = "activityId", skip_serializing_if = "Option::is_none")]
    pub activity_id: Option<String>,
    /// Can be used with instructions of types `startTransition`. Specifies the sequence flow to start.
    #[serde(rename = "transitionId", skip_serializing_if = "Option::is_none")]
    pub transition_id: Option<String>,
    /// Can be used with instructions of type `cancel`. Specifies the activity instance to cancel. Valid values are the activity instance IDs supplied by the [Get Activity Instance request](https://docs.camunda.org/manual/7.14/reference/rest/process-instance/get-activity-instances/).
    #[serde(rename = "activityInstanceId", skip_serializing_if = "Option::is_none")]
    pub activity_instance_id: Option<String>,
    /// Can be used with instructions of type `cancel`. Specifies the transition instance to cancel. Valid values are the transition instance IDs supplied by the [Get Activity Instance request](https://docs.camunda.org/manual/7.14/reference/rest/process-instance/get-activity-instances/).
    #[serde(rename = "transitionInstanceId", skip_serializing_if = "Option::is_none")]
    pub transition_instance_id: Option<String>,
    /// Can be used with instructions of type `startBeforeActivity`, `startAfterActivity`, and `startTransition`. Valid values are the activity instance IDs supplied by the Get Activity Instance request. If there are multiple parent activity instances of the targeted activity, this specifies the ancestor scope in which hierarchy the activity/transition is to be instantiated.  Example: When there are two instances of a subprocess and an activity contained in the subprocess is to be started, this parameter allows to specifiy under which subprocess instance the activity should be started.
    #[serde(rename = "ancestorActivityInstanceId", skip_serializing_if = "Option::is_none")]
    pub ancestor_activity_instance_id: Option<String>,
    /// Can be used with instructions of type cancel. Prevents the deletion of new created activity instances.
    #[serde(rename = "cancelCurrentActiveActivityInstances", skip_serializing_if = "Option::is_none")]
    pub cancel_current_active_activity_instances: Option<bool>,
}

impl ProcessInstanceModificationInstructionDto {
    pub fn new(_type: Type) -> ProcessInstanceModificationInstructionDto {
        ProcessInstanceModificationInstructionDto {
            _type,
            variables: None,
            activity_id: None,
            transition_id: None,
            activity_instance_id: None,
            transition_instance_id: None,
            ancestor_activity_instance_id: None,
            cancel_current_active_activity_instances: None,
        }
    }
}

/// **Mandatory**. One of the following values: `cancel`, `startBeforeActivity`, `startAfterActivity`, `startTransition`.  * A cancel instruction requests cancellation of a single activity instance or all instances of one activity. * A startBeforeActivity instruction requests to enter a given activity. * A startAfterActivity instruction requests to execute the single outgoing sequence flow of a given activity. * A startTransition instruction requests to execute a specific sequence flow.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "cancel")]
    Cancel,
    #[serde(rename = "startBeforeActivity")]
    StartBeforeActivity,
    #[serde(rename = "startAfterActivity")]
    StartAfterActivity,
    #[serde(rename = "startTransition")]
    StartTransition,
}

