/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceWithVariablesDtoAllOf {
    /// The id of the process instance.
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<::std::collections::HashMap<String, crate::models::VariableValueDto>>,
}

impl ProcessInstanceWithVariablesDtoAllOf {
    pub fn new() -> ProcessInstanceWithVariablesDtoAllOf {
        ProcessInstanceWithVariablesDtoAllOf {
            variables: None,
        }
    }
}


