/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProcessInstanceModificationDto {
    /// Skip execution listener invocation for activities that are started or ended as part of this request.
    #[serde(rename = "skipCustomListeners", skip_serializing_if = "Option::is_none")]
    pub skip_custom_listeners: Option<bool>,
    /// Skip execution of [input/output variable mappings](https://docs.camunda.org/manual/7.14/user-guide/process-engine/variables/#input-output-variable-mapping) for activities that are started or ended as part of this request.
    #[serde(rename = "skipIoMappings", skip_serializing_if = "Option::is_none")]
    pub skip_io_mappings: Option<bool>,
    /// JSON array of modification instructions. The instructions are executed in the order they are in.
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<Vec<crate::models::ProcessInstanceModificationInstructionDto>>,
    /// An arbitrary text annotation set by a user for auditing reasons.
    #[serde(rename = "annotation", skip_serializing_if = "Option::is_none")]
    pub annotation: Option<String>,
}

impl ProcessInstanceModificationDto {
    pub fn new() -> ProcessInstanceModificationDto {
        ProcessInstanceModificationDto {
            skip_custom_listeners: None,
            skip_io_mappings: None,
            instructions: None,
            annotation: None,
        }
    }
}


