/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceReportDto {
    /// A list of errors occurred during parsing.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<crate::models::ProblemDto>>,
    /// A list of warnings occurred during parsing.
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<Vec<crate::models::ProblemDto>>,
}

impl ResourceReportDto {
    pub fn new() -> ResourceReportDto {
        ResourceReportDto {
            errors: None,
            warnings: None,
        }
    }
}


