/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetRemovalTimeToHistoricProcessInstancesDto {
    /// The id of the process instance.
    #[serde(rename = "historicProcessInstanceIds", skip_serializing_if = "Option::is_none")]
    pub historic_process_instance_ids: Option<Vec<String>>,
    #[serde(rename = "historicProcessInstanceQuery", skip_serializing_if = "Option::is_none")]
    pub historic_process_instance_query: Option<crate::models::HistoricProcessInstanceQueryDto>,
    /// Sets the removal time to all historic process instances in the hierarchy. Value may only be `true`, as `false` is the default behavior.
    #[serde(rename = "hierarchical", skip_serializing_if = "Option::is_none")]
    pub hierarchical: Option<bool>,
    /// The date for which the instances shall be removed. Value may not be `null`.  **Note:** Cannot be set in conjunction with `clearedRemovalTime` or `calculatedRemovalTime`.
    #[serde(rename = "absoluteRemovalTime", skip_serializing_if = "Option::is_none")]
    pub absolute_removal_time: Option<String>,
    /// Sets the removal time to `null`. Value may only be `true`, as `false` is the default behavior.  **Note:** Cannot be set in conjunction with `absoluteRemovalTime` or `calculatedRemovalTime`.
    #[serde(rename = "clearedRemovalTime", skip_serializing_if = "Option::is_none")]
    pub cleared_removal_time: Option<bool>,
    /// The removal time is calculated based on the engine's configuration settings. Value may only be `true`, as `false` is the default behavior.  **Note:** Cannot be set in conjunction with `absoluteRemovalTime` or `clearedRemovalTime`.
    #[serde(rename = "calculatedRemovalTime", skip_serializing_if = "Option::is_none")]
    pub calculated_removal_time: Option<bool>,
}

impl SetRemovalTimeToHistoricProcessInstancesDto {
    pub fn new() -> SetRemovalTimeToHistoricProcessInstancesDto {
        SetRemovalTimeToHistoricProcessInstancesDto {
            historic_process_instance_ids: None,
            historic_process_instance_query: None,
            hierarchical: None,
            absolute_removal_time: None,
            cleared_removal_time: None,
            calculated_removal_time: None,
        }
    }
}


