/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetRemovalTimeToHistoricProcessInstancesDtoAllOf {
    /// The id of the process instance.
    #[serde(rename = "historicProcessInstanceIds", skip_serializing_if = "Option::is_none")]
    pub historic_process_instance_ids: Option<Vec<String>>,
    #[serde(rename = "historicProcessInstanceQuery", skip_serializing_if = "Option::is_none")]
    pub historic_process_instance_query: Option<crate::models::HistoricProcessInstanceQueryDto>,
    /// Sets the removal time to all historic process instances in the hierarchy. Value may only be `true`, as `false` is the default behavior.
    #[serde(rename = "hierarchical", skip_serializing_if = "Option::is_none")]
    pub hierarchical: Option<bool>,
}

impl SetRemovalTimeToHistoricProcessInstancesDtoAllOf {
    pub fn new() -> SetRemovalTimeToHistoricProcessInstancesDtoAllOf {
        SetRemovalTimeToHistoricProcessInstancesDtoAllOf {
            historic_process_instance_ids: None,
            historic_process_instance_query: None,
            hierarchical: None,
        }
    }
}


