/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SortTaskQueryParametersDto : Mandatory when `sortBy` is one of the following values: `processVariable`, `executionVariable`, `taskVariable`, `caseExecutionVariable` or `caseInstanceVariable`. Must be a JSON object with the properties `variable` and `type` where `variable` is a variable name and `type` is the name of a variable value type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SortTaskQueryParametersDto {
    /// The name of the variable to sort by.
    #[serde(rename = "variable", skip_serializing_if = "Option::is_none")]
    pub variable: Option<String>,
    /// The name of the type of the variable value.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<String>,
}

impl SortTaskQueryParametersDto {
    /// Mandatory when `sortBy` is one of the following values: `processVariable`, `executionVariable`, `taskVariable`, `caseExecutionVariable` or `caseInstanceVariable`. Must be a JSON object with the properties `variable` and `type` where `variable` is a variable name and `type` is the name of a variable value type.
    pub fn new() -> SortTaskQueryParametersDto {
        SortTaskQueryParametersDto {
            variable: None,
            _type: None,
        }
    }
}


