/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TriggerVariableValueDtoAllOf {
    /// Indicates whether the variable should be a local variable or not. If set to true, the variable becomes a local variable of the execution entering the target activity.
    #[serde(rename = "local", skip_serializing_if = "Option::is_none")]
    pub local: Option<bool>,
}

impl TriggerVariableValueDtoAllOf {
    pub fn new() -> TriggerVariableValueDtoAllOf {
        TriggerVariableValueDtoAllOf {
            local: None,
        }
    }
}


