/*
 * Camunda BPM REST API
 *
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VariableQueryParameterDto {
    /// Variable name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Comparison operator to be used
    #[serde(rename = "operator", skip_serializing_if = "Option::is_none")]
    pub operator: Option<Operator>,
    /// The variable value, could be of type boolean, string or number
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<serde_json::Value>,
}

impl VariableQueryParameterDto {
    pub fn new() -> VariableQueryParameterDto {
        VariableQueryParameterDto {
            name: None,
            operator: None,
            value: None,
        }
    }
}

/// Comparison operator to be used
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Operator {
    #[serde(rename = "eq")]
    Eq,
    #[serde(rename = "neq")]
    Neq,
    #[serde(rename = "gt")]
    Gt,
    #[serde(rename = "gteq")]
    Gteq,
    #[serde(rename = "lt")]
    Lt,
    #[serde(rename = "lteq")]
    Lteq,
    #[serde(rename = "like")]
    Like,
}

